### ISSUE TITLE
ReferenceError: size is not defined when calling createRequestAsPayee function

### ISSUE THREAD

**Issue by myamout** [RequestNetwork/requestNetwork.js#22]
I'm following the example from the `createRequestAsPayee.ts` test file as how to call the function.

import RequestNetwork from './dist/src/requestNetwork';
import Eth from 'ethjs';
const rn = new RequestNetwork('http://localhost:8545', 45, false);
const eth = new Eth(new Eth.HttpProvider('http://localhost:8545'));
let accounts = [];
let payer = '';
let payee = '';
const mainAsync = async () => {
    try {
        // Get accounts active on Ganache
        accounts = await eth.accounts();
        payee = accounts[1].toLowerCase();
        payer = accounts[2].toLowerCase();
        const request = await rn.requestEthereumService.createRequestAsPayee(
            payer,
            10000,
            '{"reason": "Freelance work"}',
            '',
            [],
            {from: payee}
        ).on('broadcasted', ((txHash) => {
            console.log(txHash);
        }));
        console.log(request);
    } catch(error) {
        console.log(error);
    }
};
mainAsync().catch((error) => {
    console.log(error);
});

Above is my code, this seems correct? Not sure if I'm missing anything.

**Comment by vrolland** [comment]
Hi myamout,
I just replaced `import Eth from 'ethjs';` by `const Eth = require('ethjs');` and it works like a charm.
Can you provide more information, please? Did you deploy the contract on your testrpc?

Beside, you should rather use `npm ` instead of getting the code through github. (see README.md)

PS: Next time use \` \` around your code to make it easier to read, please.

**Comment by myamout** [comment]
I'm gonna go ahead and close this because I was able to get it working after messing around some more.

**Comment by myamout** [comment]
Thanks for the help!
